#! /usr/bin/python3
import os
cmd_set = "xinput set-prop 14 \"Device Enabled\" 1"

os.system(cmd_set)

cmd_display = "xrandr --output HDMI-2 --off --output HDMI-1 --off --output DP-1 --off --output eDP-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output DP-2 --off"

os.system(cmd_display)

cmd_keyboard = 'setxkbmap -layout "us_intl"'

os.system(cmd_keyboard);
