#! /usr/bin/python3
import os
cmd_set = "xinput set-prop 14 \"Device Enabled\" 0"

os.system(cmd_set)

cmd_display = "xrandr --output DP-2-1 --off --output DP-2-2 --off --output DP-2-3 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output eDP-1 --mode 1366x768 --pos 1920x312 --rotate normal --output HDMI-2 --off --output HDMI-1 --off --output DP-2 --off --output DP-1 --off"

os.system(cmd_display)

cmd_keyboard = 'setxkbmap -layout "br"'

os.system(cmd_keyboard)
